# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SwiftDIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftDI', :path => '../'
  pod 'SwiftDILint', :path => '../'
  # Pods for SwiftDIDemo

end
